version: '3.8'

services:
  attack-server:
    build:
      context: ./attack-server
      dockerfile: Dockerfile
    container_name: attack-server
    networks:
      - log4shell-net
    ports:
      - "8080:8080"
      - "10389:10389"

  vulnerable-app:
    build:
      context: ./demo-vuln-app
      dockerfile: Dockerfile
    container_name: vulnerable-app
    networks:
      - log4shell-net
    ports:
      - "9090:9090"
    depends_on:
      - attack-server

networks:
  log4shell-net:
    driver: bridge
